-- MySQL Script generated by MySQL Workbench
-- 03/28/18 14:07:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema yhdmvc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yhdmvc` ;

-- -----------------------------------------------------
-- Schema yhdmvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yhdmvc` DEFAULT CHARACTER SET utf8 ;
USE `yhdmvc` ;

-- -----------------------------------------------------
-- Table `yhdmvc`.`yhdmvc_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yhdmvc`.`yhdmvc_user` ;

CREATE TABLE IF NOT EXISTS `yhdmvc`.`yhdmvc_user` (
  `id` VARCHAR(100) NOT NULL COMMENT '主键id',
  `login_name` VARCHAR(100) NULL COMMENT '用户登录名称',
  `display_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户显示名称',
  `password` VARCHAR(100) NULL DEFAULT NULL COMMENT '登录密码',
  `update_time` DATETIME NULL DEFAULT NULL COMMENT '本条数据的更新时间',
  `description` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户个人信息',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '使用SpringMVC搭建的一个简单系统的登陆用户';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
